name    = App-Yath-Script
author  = Chad Granum <exodist@cpan.org>
license = Perl_5
copyright_holder = Chad Granum

[RewriteVersion] ; sets dist version from main module's $VERSION
[License]
[ManifestSkip]
[Manifest]
[NextRelease]

[GatherDir]
exclude_filename = LICENSE
exclude_filename = Makefile.PL
exclude_filename = README
exclude_filename = README.md
exclude_filename = cpanfile

[ExecDir]
dir = scripts

[PodSyntaxTests]
[TestRelease]

[MetaResources]
bugtracker.web  = https://github.com/Test-More/Test2-Harness/issues
repository.url  = https://github.com/Test-More/Test2-Harness/
repository.type = git

[Prereqs]
perl          = 5.014000
Carp          = 0
File::Spec    = 0
Cwd           = 3.75
Importer      = 0.025
Getopt::Yath  = 2.000008

[Prereqs / TestRequires]
Test2::V0 = 1.302199

[Prereqs / ConfigureRequires]
ExtUtils::MakeMaker = 0

[Prereqs / DevelopRequires]
Test::Pod      = 1.41
Test::Spelling = 0.12
goto::file     = 0

[MakeMaker::Awesome]
:version = 0.26
delimiter = |
header = |if ($ENV{AUTOMATED_TESTING}) {
header = |    my $is_njh = 0;
header = |    $is_njh ||= -d '/export/home/njh';
header = |    $is_njh ||= -d '/home/njh';
header = |    $is_njh ||= lc($ENV{USER} // 'na') eq 'njh';
header = |    $is_njh ||= lc($ENV{HOME} // 'na') =~ m{njh$};
header = |    $is_njh ||= lc($ENV{PATH} // 'na') =~ m{/njh/};
header = |    die "OS unsupported\nNJH smokers are broken, aborting tests.\n"
header = |        if $is_njh;
header = |}

[CPANFile]
[MetaYAML]
[MetaJSON]

; authordep Pod::Markdown
[ReadmeFromPod / Markdown]
filename = lib/App/Yath/Script.pm
type = markdown
readme = README.md

[ReadmeFromPod / Text]
filename = lib/App/Yath/Script.pm
type = text
readme = README

[CopyFilesFromBuild]
copy = LICENSE
copy = cpanfile
copy = README
copy = README.md
copy = Makefile.PL

[Git::Check]
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = README.md
allow_dirty = cpanfile
allow_dirty = LICENSE
allow_dirty = Changes

[Git::Commit]
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = README.md
allow_dirty = cpanfile
allow_dirty = LICENSE
allow_dirty = Changes

[Git::Tag]
tag_format = script-v%v

[FakeRelease]

[BumpVersionAfterRelease]

[Git::Commit / Commit_Changes]
munge_makefile_pl = true
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = README.md
allow_dirty = cpanfile
allow_dirty = LICENSE
commit_msg = Automated Version Bump
