---
abstract: 'Captures Test2::Harness results and emits a junit xml file.'
author:
  - 'Todd E. Rinaldo <toddr@cpanel.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test2-Harness-Renderer-JUnit
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: '0'
  Storable: '0'
  Test2::Harness::Renderer: '0.001077'
  Test2::Harness::Util::HashBase: '0.001077'
  XML::Generator: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/cpanelinc/Test2-Harness-Renderer-JUnit/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/cpanelinc/Test2-Harness-Renderer-JUnit
version: '0.001077'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
