use Test2::V0;

use Test2::Harness2::Run::State;

subtest 'requires run_id' => sub {
    my $ok  = eval { Test2::Harness2::Run::State->new; 1 };
    my $err = $@;
    ok(!$ok, 'croaks without run_id');
    like($err, qr/run_id/);
};

subtest 'defaults: empty pending / running / done / results' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    is($s->run_id,  'r-1', 'run_id stored');
    is($s->pending, [],    'pending defaulted to empty');
    is($s->running, [],    'running defaulted to empty');
    is($s->done,    [],    'done defaulted to empty');
    is($s->results, {},    'results defaulted to empty');
    ok($s->is_complete, 'an empty state is vacuously complete');
};

subtest 'mark_started / mark_finished' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    ok(!defined $s->start_time,  'start_time undef before mark_started');
    ok(!defined $s->finish_time, 'finish_time undef before mark_finished');
    ok(!$s->completed,           'completed false initially');

    $s->mark_started;
    ok(defined $s->start_time, 'start_time stamped');

    my $first = $s->start_time;
    $s->mark_started;
    is($s->start_time, $first, 'mark_started is idempotent');

    $s->mark_finished;
    ok(defined $s->finish_time, 'finish_time stamped');
    ok($s->completed,           'completed flipped on');
};

subtest 'seed_pending / mark_running / mark_done' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    $s->seed_pending(qw/A B C/);
    is($s->pending, [qw/A B C/], 'pending seeded');

    $s->mark_running('A');
    is($s->pending, [qw/B C/], 'A removed from pending');
    is($s->running, [qw/A/],   'A in running');

    $s->mark_done('A');
    is($s->running, [],      'A removed from running');
    is($s->done,    [qw/A/], 'A landed in done');

    my $ok  = eval { $s->mark_running('not-a-real-id'); 1 };
    my $err = $@;
    ok(!$ok, 'mark_running croaks for unknown id');
    like($err, qr/not pending/);

    $ok  = eval { $s->mark_done('B'); 1 };
    $err = $@;
    ok(!$ok, 'mark_done croaks when job not running');
    like($err, qr/not running/);
};

subtest 'mark_skipped moves pending -> done' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    $s->seed_pending('A');
    $s->mark_skipped('A');
    is($s->pending, [],      'pending empty');
    is($s->done,    [qw/A/], 'done has A');
    ok($s->is_complete, 'complete after skip');
};

subtest 'record_job_result / seed_job_result' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');

    $s->seed_job_result('J', queued_at => 1, file => 'old');
    is($s->results->{J}{queued_at}, 1,     'seeded queued_at');
    is($s->results->{J}{file},      'old', 'seeded file');

    $s->seed_job_result('J', file => 'newer');
    is($s->results->{J}{file}, 'old', 'seed_job_result does not overwrite');

    $s->record_job_result('J', file => 'newer', pass => 1);
    is($s->results->{J}{file}, 'newer', 'record_job_result overwrites');
    is($s->results->{J}{pass}, 1,       'record_job_result added pass');
};

subtest 'latch_aborted_reason is first-writer-wins' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    $s->latch_aborted_reason('first');
    $s->latch_aborted_reason('second');
    is($s->aborted_reason, 'first', 'first reason wins');
};

subtest 'identity setters (auto-generated by Object::HashBase)' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    $s->set_running_harness_uuid('h-uuid');
    $s->set_collector_uuid('c-uuid');
    $s->set_bus_address('bus://example');
    $s->set_running_session_uuid('sess-uuid');

    is($s->running_harness_uuid, 'h-uuid',        'running_harness_uuid');
    is($s->collector_uuid,       'c-uuid',        'collector_uuid');
    is($s->bus_address,          'bus://example', 'bus_address');
    is($s->running_session_uuid, 'sess-uuid',     'running_session_uuid');
};

subtest 'resources_started / resources_torn_down idempotency flags' => sub {
    my $s = Test2::Harness2::Run::State->new(run_id => 'r-1');
    ok(!$s->resources_started_flag,   'flag off initially');
    ok(!$s->resources_torn_down_flag, 'torn-down flag off initially');

    $s->mark_resources_started;
    ok($s->resources_started_flag, 'started flag flipped');

    $s->mark_resources_torn_down;
    ok($s->resources_torn_down_flag, 'torn-down flag flipped');
};

subtest 'TO_JSON / rehydrate round trip' => sub {
    my $s = Test2::Harness2::Run::State->new(
        run_id     => 'r-rt',
        created_at => 12345,
    );
    $s->seed_pending(qw/A B/);
    $s->mark_running('A');
    $s->record_job_result('A', pass => 1, completed_at => 100);
    $s->set_exit_summary({pass => 1, fail => 0});
    $s->mark_started;
    $s->mark_finished;
    $s->set_running_harness_uuid('h-uuid');

    my $h = $s->TO_JSON;
    is(ref($h),                'HASH',  'returns a hashref');
    is($h->{run_id},           'r-rt',  'run_id present');
    is($h->{created_at},       12345,   'created_at present');
    is($h->{pending},          [qw/B/], 'pending in TO_JSON');
    is($h->{running},          [qw/A/], 'running in TO_JSON');
    is($h->{results}{A}{pass}, 1,       'per-job results in TO_JSON');
    ok($h->{completed}, 'completed flag in TO_JSON');

    my $s2 = Test2::Harness2::Run::State->rehydrate($h);
    is($s2->run_id,               $s->run_id, 'rehydrated run_id');
    is($s2->pending,              [qw/B/],    'rehydrated pending');
    is($s2->running,              [qw/A/],    'rehydrated running');
    is($s2->results->{A}{pass},   1,          'rehydrated results');
    is($s2->running_harness_uuid, 'h-uuid',   'rehydrated identity');
    ok($s2->completed, 'rehydrated completed');
};

done_testing;
