#!/usr/bin/env perl
use Test2::Require::Module 'Test::Class::Moose::Runner';

my $file = shift @ARGV;
require $file;
require Test::Class::Moose::Runner;
Test::Class::Moose::Runner->import;
Test::Class::Moose::Runner->new->runtests();

__END__

=pod

=encoding UTF-8

=head1 NAME


=head1 DESCRIPTION

=head1 SOURCE

The source code repository for Test2-Harness can be found at
F<http://github.com/Test-More/Test2-Harness/>.

=head1 MAINTAINERS

=over 4

=item Chad Granum E<lt>exodist@cpan.orgE<gt>

=back

=head1 AUTHORS

=over 4

=item Chad Granum E<lt>exodist@cpan.orgE<gt>

=back

=head1 COPYRIGHT

Copyright 2017 Chad Granum E<lt>exodist7@gmail.comE<gt>.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

See F<http://dev.perl.org/licenses/>

=cut
